### ISSUE TITLE
Submenu bumper height

### ISSUE THREAD

**Issue by khnbb** [khnbb/nbbwww73#3]
Something funny is going on with the padding/height on subpages like http://freshbeer.newbelgium.com/Beer.aspx where it's not pushing the content down as much as it should.  Probably something in scripts/rd2014/nbbrd2014.js.

**Comment by miked00** [comment]
Kurt,  You were correct.  The html structure changed just a bit and I had to modify the js file to accommodate.  This should be fixed now.
