### ISSUE TITLE
Beer detail pages not showing beer content

### ISSUE THREAD

**Issue by khnbb** [khnbb/nbbwww73#4]
Try fat tire for example, though it appears to be happening for all of them.

http://freshbeer.newbelgium.com/beer/detail.aspx?id=7c5b394b-d7b7-486a-ac9a-316256a7b0ee

**Comment by miked00** [comment]
This has been fixed.  I changed some of the code on the beer module and had to delete out the beer module and then swap out the page template and add back in the beer module.
