### ISSUE TITLE
Submenu should only pull second level

### ISSUE THREAD

**Issue by khnbb** [khnbb/nbbwww73#8]
Compare the menu on http://www.newbelgium.com/Brewery.aspx and then http://freshbeer.newbelgium.com/Brewery.aspx

Then compare http://www.newbelgium.com/Brewery/tasting-room/visit-us.aspx and http://freshbeer.newbelgium.com/Brewery/tasting-room.aspx

note that on freshbeer, the visit-us page is showing subpages under itself but should actually show subpages under the brewery root node.

=)

**Comment by miked00** [comment]
Kurt, I have fixed this issue and have the correct levels showing on the sub menu.
